name: Continuous Integration

on:
  pull_request:
    branches: ["dev"]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: run install and build
        run: |
          npm install
          npm run build
